"preserve_hierarchy": true

"pull_request_labels": [
  "crowdin",
  "l10n"
]

"files": [
  {
    "source": "/content/**/*.fr.md",
    "translation": "/l10n/%two_letters_code%/**/%original_file_name%",
  }
]
